// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ddlab.client.jaxrpc;


public class InvalidZodiacSignException extends java.lang.Exception {
    private java.lang.String message;
    
    
    public InvalidZodiacSignException(java.lang.String message) {
        super(message);
        this.message = message;
    }
    
    public java.lang.String getMessage() {
        return message;
    }
}
