// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ddlab.client.jaxrpc;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.util.exception.LocalizableExceptionAdapter;

public class InvalidZodiacSignException_SOAPBuilder implements SOAPInstanceBuilder {
    private com.ddlab.client.jaxrpc.InvalidZodiacSignException _instance;
    private java.lang.String message;
    private static final int myMESSAGE_INDEX = 0;
    
    public InvalidZodiacSignException_SOAPBuilder() {
    }
    
    
    public InvalidZodiacSignException_SOAPBuilder(java.lang.String message) {
        this.message = message;
    }
    
    public void setMessage(java.lang.String message) {
        this.message = message;
    }
    
    public int memberGateType(int memberIndex) {
        switch (memberIndex) {
            case myMESSAGE_INDEX:
                return GATES_CONSTRUCTION | REQUIRES_INITIALIZATION;
            default:
                throw new IllegalArgumentException();
        }
    }
    
    public void construct() {
        _instance = new com.ddlab.client.jaxrpc.InvalidZodiacSignException(message);
    }
    
    public void setMember(int index, java.lang.Object memberValue) {
        try {
            switch(index) {
                case myMESSAGE_INDEX:
                    setMessage((java.lang.String)memberValue);
                    break;
                default:
                    throw new java.lang.IllegalArgumentException();
            }
        }
        catch (java.lang.RuntimeException e) {
            throw e;
        }
        catch (java.lang.Exception e) {
            throw new DeserializationException(new LocalizableExceptionAdapter(e));
        }
    }
    
    public void initialize() {
    }
    
    public void setInstance(java.lang.Object instance) {
        _instance = (com.ddlab.client.jaxrpc.InvalidZodiacSignException)instance;
    }
    
    public java.lang.Object getInstance() {
        return _instance;
    }
}
