// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ddlab.client.jaxrpc;

public interface ZodiacCalculator extends java.rmi.Remote {
    public java.lang.String getZodiacSign(int int_1, int int_2, int int_3) throws 
        com.ddlab.client.jaxrpc.InvalidZodiacSignException,  java.rmi.RemoteException;
}
