// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ddlab.client.jaxrpc;


public class ZodiacCalculator_getZodiacSign_ResponseStruct {
    protected java.lang.String result;
    
    public ZodiacCalculator_getZodiacSign_ResponseStruct() {
    }
    
    public ZodiacCalculator_getZodiacSign_ResponseStruct(java.lang.String result) {
        this.result = result;
    }
    
    public java.lang.String getResult() {
        return result;
    }
    
    public void setResult(java.lang.String result) {
        this.result = result;
    }
}
