// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ddlab.client.jaxrpc;

import com.sun.xml.rpc.server.http.MessageContextProperties;
import com.sun.xml.rpc.streaming.*;
import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.soap.SOAPConstants;
import com.sun.xml.rpc.encoding.soap.SOAP12Constants;
import com.sun.xml.rpc.encoding.literal.*;
import com.sun.xml.rpc.soap.streaming.*;
import com.sun.xml.rpc.soap.message.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.soap.SOAPEncodingConstants;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;
import javax.xml.namespace.QName;
import java.rmi.RemoteException;
import java.util.Iterator;
import java.lang.reflect.*;
import java.lang.Class;
import com.sun.xml.rpc.client.SenderException;
import com.sun.xml.rpc.client.*;
import com.sun.xml.rpc.client.http.*;
import javax.xml.rpc.handler.*;
import javax.xml.rpc.JAXRPCException;
import javax.xml.rpc.soap.SOAPFaultException;

public class ZodiacCalculator_Stub
    extends com.sun.xml.rpc.client.StubBase
    implements com.ddlab.client.jaxrpc.ZodiacCalculator {
    
    
    
    /*
     *  public constructor
     */
    public ZodiacCalculator_Stub(HandlerChain handlerChain) {
        super(handlerChain);
        _setProperty(ENDPOINT_ADDRESS_PROPERTY, "http://localhost:8080/zodiaccalculatorservice_jaxrpc_manyclients/ZodiacCalculatorService?WSDL");
    }
    
    
    /*
     *  implementation of getZodiacSign
     */
    public java.lang.String getZodiacSign(int int_1, int int_2, int int_3)
        throws com.ddlab.client.jaxrpc.InvalidZodiacSignException, java.rmi.RemoteException {
        
        try {
            
            StreamingSenderState _state = _start(_handlerChain);
            
            InternalSOAPMessage _request = _state.getRequest();
            _request.setOperationCode(getZodiacSign_OPCODE);
            com.ddlab.client.jaxrpc.ZodiacCalculator_getZodiacSign_RequestStruct _myZodiacCalculator_getZodiacSign_RequestStruct =
                new com.ddlab.client.jaxrpc.ZodiacCalculator_getZodiacSign_RequestStruct();
            
            _myZodiacCalculator_getZodiacSign_RequestStruct.setInt_1(int_1);
            _myZodiacCalculator_getZodiacSign_RequestStruct.setInt_2(int_2);
            _myZodiacCalculator_getZodiacSign_RequestStruct.setInt_3(int_3);
            
            SOAPBlockInfo _bodyBlock = new SOAPBlockInfo(ns1_getZodiacSign_getZodiacSign_QNAME);
            _bodyBlock.setValue(_myZodiacCalculator_getZodiacSign_RequestStruct);
            _bodyBlock.setSerializer(ns1_myZodiacCalculator_getZodiacSign_RequestStruct_SOAPSerializer);
            _request.setBody(_bodyBlock);
            
            _state.getMessageContext().setProperty(HttpClientTransport.HTTP_SOAPACTION_PROPERTY, "");
            
            _send((java.lang.String) _getProperty(ENDPOINT_ADDRESS_PROPERTY), _state);
            
            com.ddlab.client.jaxrpc.ZodiacCalculator_getZodiacSign_ResponseStruct _myZodiacCalculator_getZodiacSign_ResponseStruct = null;
            Object _responseObj = _state.getResponse().getBody().getValue();
            if (_responseObj instanceof SOAPDeserializationState) {
                _myZodiacCalculator_getZodiacSign_ResponseStruct =
                    (com.ddlab.client.jaxrpc.ZodiacCalculator_getZodiacSign_ResponseStruct)((SOAPDeserializationState)_responseObj).getInstance();
            } else {
                _myZodiacCalculator_getZodiacSign_ResponseStruct =
                    (com.ddlab.client.jaxrpc.ZodiacCalculator_getZodiacSign_ResponseStruct)_responseObj;
            }
            
            return _myZodiacCalculator_getZodiacSign_ResponseStruct.getResult();
        } catch (com.ddlab.client.jaxrpc.InvalidZodiacSignException e) {
            throw e;
        } catch (RemoteException e) {
            if (e.detail instanceof com.sun.xml.rpc.util.HeaderFaultException) {
                com.sun.xml.rpc.util.HeaderFaultException hfe = (com.sun.xml.rpc.util.HeaderFaultException) e.detail;
                SOAPHeaderBlockInfo headerBlock = (SOAPHeaderBlockInfo) hfe.getObject();
                java.lang.Object obj = headerBlock.getValue();
            }
            // let this one through unchanged
            throw e;
        } catch (JAXRPCException e) {
            throw new RemoteException(e.getMessage(), e);
        } catch (Exception e) {
            if (e instanceof RuntimeException) {
                throw (RuntimeException)e;
            } else {
                throw new RemoteException(e.getMessage(), e);
            }
        }
    }
    
    
    /*
     *  this method deserializes the request/response structure in the body
     */
    protected void _readFirstBodyElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState  state) throws Exception {
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case getZodiacSign_OPCODE:
                _deserialize_getZodiacSign(bodyReader, deserializationContext, state);
                break;
            default:
                throw new SenderException("sender.response.unrecognizedOperation", java.lang.Integer.toString(opcode));
        }
    }
    
    
    
    /*
     * This method deserializes the body of the getZodiacSign operation.
     */
    private void _deserialize_getZodiacSign(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        java.lang.Object myZodiacCalculator_getZodiacSign_ResponseStructObj =
            ns1_myZodiacCalculator_getZodiacSign_ResponseStruct_SOAPSerializer.deserialize(ns1_getZodiacSign_getZodiacSignResponse_QNAME,
                bodyReader, deserializationContext);
        
        SOAPBlockInfo bodyBlock = new SOAPBlockInfo(ns1_getZodiacSign_getZodiacSignResponse_QNAME);
        bodyBlock.setValue(myZodiacCalculator_getZodiacSign_ResponseStructObj);
        state.getResponse().setBody(bodyBlock);
    }
    
    /*
     *  this method deserializes fault responses
     */
    protected Object _readBodyFaultElement(XMLReader bodyReader, SOAPDeserializationContext deserializationContext, StreamingSenderState state) throws Exception {
        Object faultInfo = null;
        int opcode = state.getRequest().getOperationCode();
        switch (opcode) {
            case getZodiacSign_OPCODE:
                faultInfo = myZodiacCalculator_getZodiacSign_Fault_SOAPSerializer.deserialize(null, bodyReader, deserializationContext);
                break;
            default:
                return super._readBodyFaultElement(bodyReader, deserializationContext, state);
        }
        return faultInfo;
    }
    
    
    public java.lang.String _getDefaultEnvelopeEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public java.lang.String _getImplicitEnvelopeEncodingStyle() {
        return "";
    }
    
    public java.lang.String _getEncodingStyle() {
        return SOAPNamespaceConstants.ENCODING;
    }
    
    public void _setEncodingStyle(java.lang.String encodingStyle) {
        throw new UnsupportedOperationException("cannot set encoding style");
    }
    
    
    
    
    
    /*
     * This method returns an array containing (prefix, nsURI) pairs.
     */
    protected java.lang.String[] _getNamespaceDeclarations() {
        return myNamespace_declarations;
    }
    
    /*
     * This method returns an array containing the names of the headers we understand.
     */
    public javax.xml.namespace.QName[] _getUnderstoodHeaders() {
        return understoodHeaderNames;
    }
    
    public void _initialize(InternalTypeMappingRegistry registry) throws Exception {
        super._initialize(registry);
        ns1_myZodiacCalculator_getZodiacSign_ResponseStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.ddlab.client.jaxrpc.ZodiacCalculator_getZodiacSign_ResponseStruct.class, ns1_getZodiacSignResponse_TYPE_QNAME);
        ns1_myZodiacCalculator_getZodiacSign_RequestStruct_SOAPSerializer = (CombinedSerializer)registry.getSerializer(SOAPConstants.NS_SOAP_ENCODING, com.ddlab.client.jaxrpc.ZodiacCalculator_getZodiacSign_RequestStruct.class, ns1_getZodiacSign_TYPE_QNAME);
        ((Initializable)myZodiacCalculator_getZodiacSign_Fault_SOAPSerializer).initialize(registry);
    }
    
    private static final javax.xml.namespace.QName _portName = new QName("http://deba.org/wsdl", "ZodiacCalculatorPort");
    private static final int getZodiacSign_OPCODE = 0;
    private final CombinedSerializer myZodiacCalculator_getZodiacSign_Fault_SOAPSerializer = new ReferenceableSerializerImpl(DONT_SERIALIZE_AS_REF,
        new com.ddlab.client.jaxrpc.ZodiacCalculator_getZodiacSign_Fault_SOAPSerializer(ENCODE_TYPE, NOT_NULLABLE));
    private static final javax.xml.namespace.QName ns1_getZodiacSign_getZodiacSign_QNAME = new QName("http://deba.org/wsdl", "getZodiacSign");
    private static final javax.xml.namespace.QName ns1_getZodiacSign_TYPE_QNAME = new QName("http://deba.org/wsdl", "getZodiacSign");
    private CombinedSerializer ns1_myZodiacCalculator_getZodiacSign_RequestStruct_SOAPSerializer;
    private static final javax.xml.namespace.QName ns1_getZodiacSign_getZodiacSignResponse_QNAME = new QName("http://deba.org/wsdl", "getZodiacSignResponse");
    private static final javax.xml.namespace.QName ns1_getZodiacSignResponse_TYPE_QNAME = new QName("http://deba.org/wsdl", "getZodiacSignResponse");
    private CombinedSerializer ns1_myZodiacCalculator_getZodiacSign_ResponseStruct_SOAPSerializer;
    private static final java.lang.String[] myNamespace_declarations =
                                        new java.lang.String[] {
                                            "ns0", "http://deba.org/types",
                                            "ns1", "http://deba.org/wsdl"
                                        };
    
    private static final QName[] understoodHeaderNames = new QName[] {  };
}
