// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.ddlab.client.jaxrpc;


public class ZodiacCalculator_getZodiacSign_RequestStruct {
    protected int int_1;
    protected int int_2;
    protected int int_3;
    
    public ZodiacCalculator_getZodiacSign_RequestStruct() {
    }
    
    public ZodiacCalculator_getZodiacSign_RequestStruct(int int_1, int int_2, int int_3) {
        this.int_1 = int_1;
        this.int_2 = int_2;
        this.int_3 = int_3;
    }
    
    public int getInt_1() {
        return int_1;
    }
    
    public void setInt_1(int int_1) {
        this.int_1 = int_1;
    }
    
    public int getInt_2() {
        return int_2;
    }
    
    public void setInt_2(int int_2) {
        this.int_2 = int_2;
    }
    
    public int getInt_3() {
        return int_3;
    }
    
    public void setInt_3(int int_3) {
        this.int_3 = int_3;
    }
}
