
package com.ddlab.client.metro;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-hudson-28-
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZodiacCalculatorImplService", targetNamespace = "http://server.metro.webservice.ddlab.com/", wsdlLocation = "file:/F:/advancedworkspace/advanced1/zodiaccalculatorservice_metro_metroclients/config/ZodiacCalculatorService.wsdl")
public class ZodiacCalculatorImplService
    extends Service
{

    private final static URL ZODIACCALCULATORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ZODIACCALCULATORIMPLSERVICE_EXCEPTION;
    private final static QName ZODIACCALCULATORIMPLSERVICE_QNAME = new QName("http://server.metro.webservice.ddlab.com/", "ZodiacCalculatorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/F:/advancedworkspace/advanced1/zodiaccalculatorservice_metro_metroclients/config/ZodiacCalculatorService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZODIACCALCULATORIMPLSERVICE_WSDL_LOCATION = url;
        ZODIACCALCULATORIMPLSERVICE_EXCEPTION = e;
    }

    public ZodiacCalculatorImplService() {
        super(__getWsdlLocation(), ZODIACCALCULATORIMPLSERVICE_QNAME);
    }

    public ZodiacCalculatorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZODIACCALCULATORIMPLSERVICE_QNAME, features);
    }

    public ZodiacCalculatorImplService(URL wsdlLocation) {
        super(wsdlLocation, ZODIACCALCULATORIMPLSERVICE_QNAME);
    }

    public ZodiacCalculatorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZODIACCALCULATORIMPLSERVICE_QNAME, features);
    }

    public ZodiacCalculatorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZodiacCalculatorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZodiacCalculatorImpl
     */
    @WebEndpoint(name = "ZodiacCalculatorImplPort")
    public ZodiacCalculatorImpl getZodiacCalculatorImplPort() {
        return super.getPort(new QName("http://server.metro.webservice.ddlab.com/", "ZodiacCalculatorImplPort"), ZodiacCalculatorImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZodiacCalculatorImpl
     */
    @WebEndpoint(name = "ZodiacCalculatorImplPort")
    public ZodiacCalculatorImpl getZodiacCalculatorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.metro.webservice.ddlab.com/", "ZodiacCalculatorImplPort"), ZodiacCalculatorImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZODIACCALCULATORIMPLSERVICE_EXCEPTION!= null) {
            throw ZODIACCALCULATORIMPLSERVICE_EXCEPTION;
        }
        return ZODIACCALCULATORIMPLSERVICE_WSDL_LOCATION;
    }

}
