
package com.ddlab.client.metro;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.1-hudson-28-
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZodiacCalculatorImpl", targetNamespace = "http://server.metro.webservice.ddlab.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZodiacCalculatorImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws InvalidZodiacSignException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getZodiacSign", targetNamespace = "http://server.metro.webservice.ddlab.com/", className = "com.ddlab.client.metro.GetZodiacSign")
    @ResponseWrapper(localName = "getZodiacSignResponse", targetNamespace = "http://server.metro.webservice.ddlab.com/", className = "com.ddlab.client.metro.GetZodiacSignResponse")
    @Action(input = "http://server.metro.webservice.ddlab.com/ZodiacCalculatorImpl/getZodiacSignRequest", output = "http://server.metro.webservice.ddlab.com/ZodiacCalculatorImpl/getZodiacSignResponse", fault = {
        @FaultAction(className = InvalidZodiacSignException_Exception.class, value = "http://server.metro.webservice.ddlab.com/ZodiacCalculatorImpl/getZodiacSign/Fault/InvalidZodiacSignException")
    })
    public String getZodiacSign(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws InvalidZodiacSignException_Exception
    ;

}
